### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jlt24** [roccomuso/iot-433mhz#27]
sudo  npm install iot-433mhz -g --unsafe-perm 

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})

> serialport@4.0.1 install /usr/local/lib/node_modules/iot-433mhz/node_modules/serialport
> node-pre-gyp install --fallback-to-build

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! serialport@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@4.0.1 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.32+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "iot-433mhz" "-g" "--unsafe-perm"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by roccomuso** [comment]
Hi friend,

Are you installing it on a Raspberry PI?
Could you paste your `uname -a` output?

I'm considering to write some automated-tests soon to make sure to have a successfull installation on different platforms with different versions of node. By the way I'll suggest to update your node version to v4.4 at least.

Let me know.

**Comment by jlt24** [comment]
Yeah installing on raspberry pi.  I'll try updating node to version 4.4.
Linux raspberrypi 4.4.32+ #924 Tue Nov 15 18:06:42 GMT 2016 armv6l GNU/Linux

**Comment by jlt24** [comment]
OK. I got it working after your suggestion of updating node to 4.4.  Is
there a way through the web interface to detect a new rf code?  When I try to add an alarm I only get the 

-choose-   trigger code

but can't choose any code.  In the console I see the code reading as "More than one code reference in DB"

**Comment by roccomuso** [comment]
@jlt24,

1. Did you connect the arduino and the 433mhz RF receiver/sender?
2. Did you upload the sketch on that arduino?
3. Did you press "ignore" on that code when a snackbar jumped out on the user interface? if so, you should go to the menu and from the ignored codes see that code and remove it. (An ignored code can't be attached to the alarm-card).

If the RF 433mhz device is supported by the library, and everything is well wired, you should see the code appear on the left bottom screen, and then be able to attach it to an alarm card.
Could you paste here the console output too?

**Comment by jlt24** [comment]
Thanks for your help.  
1. Did you connect the arduino and the 433mhz RF receiver/sender? I just have the receiver connected to the arduino as of now.
2. Did you upload the sketch on that arduino? yes.  And verified it reads the rf codes. 
3. Did you press "ignore" on that code when a snackbar jumped out on the user interface? if so, you should     go to the menu and from the ignored codes see that code and remove it. (An ignored code can't be     attached to the alarm-card).  I didn't ignore the code because I never saw the code pop up on the bottom left.  

I'm thinking of starting over from scratch and see where that gets me,

The console.html page: shows lines below every time the code is read.  
More than one code reference in DB
More than one code reference in DB
More than one code reference in DB
More than one code reference in DB
More than one code reference in DB

**Comment by jlt24** [comment]
OK.  I got it to work.  I cleared out the rfcodes.db file and that seems to have done the job.  Oddly enough though I had to clear it out twice and trigger the rf as soon and the server started up.

**Comment by roccomuso** [comment]
@jlt24 weird. The DB files are handled by **NeDB**. Once every 12 hours they're automatically compacted. Moreover NeDB will refuse to start if more than 10% of the datafile is corrupt and it doesn't seem your case.

Btw any feedback is appreciated ;)

**Comment by roccomuso** [comment]
Close for inactivity.
