### ISSUE TITLE
During installation - Tried to download(404)

### ISSUE THREAD

**Issue by marekhattas** [roccomuso/iot-433mhz#31]
Hello, i got this message during installation

```
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.6/serialport-v4.0.6-node-v46-linux-arm.tar.gz 

node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.6 and node@4.4.7 (node-v46 ABI) (falling back to source compile with node-gyp) 
```

**Comment by roccomuso** [comment]
Which OS are you on?

That one is the whole log? could you past it entirely?
The serialport dependency is not pre-compiled for ARM.
So basically that is an attempt to compile it with node-gyp.
Did you launch the `sudo npm install -g iot-433mhz --unsafe-perm` command right?

**Comment by marekhattas** [comment]
RASPBIAN JESSIE LITE

`Linux raspberrypi 4.4.38+ #938 Thu Dec 15 15:17:54 GMT 2016 armv6l GNU/Linux`
`PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"`

**Comment by roccomuso** [comment]
@marekhattas Watch updated comment above

**Comment by marekhattas** [comment]
yes i did

**Comment by roccomuso** [comment]
@marekhattas 
Could you past the whole output?

Try with this command:
`sudo npm install -g iot-433mhz --unsafe-perm --build-from-source`

**Comment by roccomuso** [comment]
@marekhattas did you solve the issue?

**Comment by marekhattas** [comment]
Hi,,I try it again with this command and everything is ok... weird

**Comment by roccomuso** [comment]
@marekhattas ok, feel free to submit feedbacks ;)
