### ISSUE TITLE
CC1101

### ISSUE THREAD

**Issue by Radstake** [roccomuso/iot-433mhz#37]
Hi,
I have a raspberry with a USB transmitter receiver CUL433. When I run the FHEM server, it detected the tranmitter receiver at /dev/ttyACM0 (ccconf freq:433.920MHz bWidth:325KHz rAmpl:42dB sens:4dB) The IOT 433Mhz application doest see anyting. Any idears?

**Comment by roccomuso** [comment]
Are you using the arduino and sketch I posted?
did you read the whole guide?

**Comment by Radstake** [comment]
Hi,

Thanks for your reaction. I did. I'm not using the Ardino, but a Cul433 USB Device directly into the raspberry. It is detected as TTYACM0 device.

**Comment by roccomuso** [comment]
Yeah but this is not supposed to work.
Raw signals must be mapped in an agreed format between the device and iot-433mhz.
The arduino's sketch translates raw signals into messages understood by iot-433mhz core.

I don't know the serial output of the CUL433.

**Comment by Radstake** [comment]
Ah check, thanks. I saw that FHEM (pearl homeautomation) flashes the Device accordingly. I'll try that. Thanks anyway and your application look amAzing!

**Comment by roccomuso** [comment]
@Radstake thank you. ;)
Feel free to open again the issue if you have any update.
