### ISSUE TITLE
API and CORS

### ISSUE THREAD

**Issue by cosiwankenobi** [roccomuso/iot-433mhz#40]
Calling an API from an external webserver ends with a cross-origin error:
"
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
"
It seems as your APIs don't allow cross-origin calls. Is it correct?

**Comment by roccomuso** [comment]
You're right.
I've released the `v1.0.6` right now.
With CORS suppport, commit 199594c075e6a61d85115bc8e16a4bdd5a57c3e1.

Intall the latest and try.

**Comment by cosiwankenobi** [comment]
Yes, now it works fine.
Thank you.

**Comment by roccomuso** [comment]
You sure? I saw you reopened the issue.
let me know

**Comment by cosiwankenobi** [comment]
... sorry, now i can call the APIs, but i'm getting a 204 response (no content) and the payload is empty. I'm trying to call /api/codes/all and only when i call it from a page inside the iot-433mhz express server i get the correct payload.

**Comment by roccomuso** [comment]
ok, can you paste some example?

**Comment by cosiwankenobi** [comment]
ok. this is the (old-fashioned, i know) code i'm using to make the call. It's test.html

```javascript
    var xhr = new XMLHttpRequest();
    xhr.open('GET', 'http://localhost:8080/api/codes/all', true);
    xhr.setRequestHeader("Content-type", "application/json");
    xhr.setRequestHeader('Authorization',       'Basic cm9vdDpyb290');
    xhr.withCredentials = true;
    xhr.send();
    xhr.onreadystatechange = processRequest;
    function processRequest(e) {
    if (xhr.readyState == 4) {
        document.getElementById("output").innerHTML = xhr.responseText;
      }
    }

```

The attachment "from locahost 8080" is what i get when i put test.html in the "www" folder of iot-433mhz
<img width="1309" alt="from localhost8080" src="https://user-images.githubusercontent.com/19464460/40456996-7dfc6592-5ef4-11e8-8715-d16a7b74e990.png">

The attachment "from localhost80" is what i get when the page test.html (the very same page) is in the documentroot af an apache2 server running on the same machine
<img width="1306" alt="from localhost80" src="https://user-images.githubusercontent.com/19464460/40457065-c2161962-5ef4-11e8-9b4b-e08a1745c4d4.png">

**Comment by cosiwankenobi** [comment]
I found a workaround. It seems as one cannot use authentication if CORS is allowing connections from any origin (*). Also, Access-Control-Allow-Headers CORS header needs to be set to true.
I change the code in server.js:

```javascript
var corsOptions = {
  origin: 'http://localhost',
  optionsSuccessStatus: 200, // some legacy browsers (IE11, various SmartTVs) choke on 204
  credentials: true
}

app.use(cors(corsOptions))
```

and now it works. Sure, it works only for requests sent by localhost:80...

**Comment by roccomuso** [comment]
OK it makes sense..
But, let's try to support also other origins, try with :
```javascript
origin: function(origin, cb) {
  cb(null, true)
}
```
And let me know.
If it works even outside localhost, I'll fix it and merge it.

**Comment by cosiwankenobi** [comment]
OK it works.
So the code for CORS in server.js is:

```javascript
 // enable cors
var corsOptions = {
  origin: function(origin, cb) {
    cb(null, true)
  },
  optionsSuccessStatus: 200, // some legacy browsers (IE11, various SmartTVs) choke on 204
  credentials: true
}
app.use(cors(corsOptions))
```

**Comment by roccomuso** [comment]
Done. It will be released asap.
