### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Clark2309** [roccomuso/iot-433mhz#41]
Hi,
I'm trying to submit some weather value to my smart home receiver. After long searching in web I got no result. Hope you can give me some tip.

I have temperature and humidity in my sender arduino. But I don't know, how to encode and what protocol to use to send it to my receiver. I'm using simple RCswitch lib.

Thanks in advance.
Christof

**Comment by roccomuso** [comment]
Online you can find tons of guide on how to send data over 433mhz using cheap radio transmitter/receiver. With wiring sample and code.
