### ISSUE TITLE
can't make windows 10 install

### ISSUE THREAD

**Issue by alexmed** [roccomuso/iot-433mhz#43]
hello, i've tried to install at 2 win pc's but stuck with error

i've attached log although the CMD windows shows some different errors - screen also attached

can you please  advice whats possible to do about?
i have Python 27 installed and having Visual Studio 2017 (community) as well

[2019-05-20T08_28_34_672Z-debug.log](https://github.com/roccomuso/iot-433mhz/files/3196961/2019-05-20T08_28_34_672Z-debug.log)

here is screenshots of CMD prompt (a bit  differes from LOG file content)
![2019-05-20_113432](https://user-images.githubusercontent.com/10050173/58007850-d030a000-7af3-11e9-9a7e-f992a04fdcf8.png)
![2019-05-20_113502](https://user-images.githubusercontent.com/10050173/58007851-d030a000-7af3-11e9-863f-ab6f32a8aab7.png)
![2019-05-20_113523](https://user-images.githubusercontent.com/10050173/58007852-d0c93680-7af3-11e9-86ea-1f4e9637aac1.png)
![2019-05-20_113544](https://user-images.githubusercontent.com/10050173/58007853-d0c93680-7af3-11e9-9eeb-fa091bb56607.png)

**Comment by roccomuso** [comment]
The problem is that you're using `node 10` or latest versions and serialport 4.0.7 dependency is not available for that version.
Try to use node version `6.2.1`.
